[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_oapp = "9U2hyeVcSYHicYoU2E6EG3gwpfd7QZYJy64crYxF5ZpA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/lsz2/my_solana_wallet.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 10000000 sdk/tests/**/*.test.ts"
